name: ci
on:
  pull_request:
    branches: [master]
    paths:
      - "package.json"
      - "src/**"
      - "data/**"
      - ".github/workflows/ci.yml"
  push:
    branches: [master]
    paths:
      - "package.json"
      - "src/**"
      - "data/**"
      - ".github/workflows/ci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm i
      - run: npm run astro check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: sleep 60
        shell: bash
        if: contains(github.ref, 'master')
      - run: node scripts/generateCache.mjs
        if: contains(github.ref, 'master')
